# Generated by Django 2.1.1 on 2018-09-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('toy_category', models.CharField(default='', max_length=20)),
                ('release_date', models.DateTimeField()),
                ('was_include_in_home', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
